// One headless arena game: some seats played by the baseline `simple-ai-client`, the others by the candidate.
//
// Bundled by `tools/arena.js`, which copies both variants (git refs or directories) into a scratch directory and
// generates the `arena:variants` module this imports. Both copies of the AI share one copy of everything else, so they
// play the same game with the same classes; see docs/arena.md.
//
// It is `run.ts` with the AI seats swapped: same seeding, same plugin list (with the installed AI's line replaced by
// the two variants' `registerRules` and `registerStrategies`, in the same position), same stop at `turn:start`. That
// is what lets `--self-check` reproduce the conformance fixture's checksums.
//
// Emits one JSON document on stdout, between the markers below.

// Must stay first: it seeds `Math.random` before any engine module evaluates.
import { config, mathRandomCalls, random } from './lib/seed';

import Built from '@civ-clone/core-world/Rules/Built';
import City from '@civ-clone/core-city/City';
import Effect from '@civ-clone/core-rule/Effect';
import Player from '@civ-clone/core-player/Player';
// @ts-ignore: generated by `tools/arena.js` and resolved by its esbuild plugin. In the position `run.ts` imports
//  `SimpleAIClient`, so modules evaluate in the same order.
import variants from 'arena:variants';
import { checksum, snapshot } from './lib/checksum';
import { advanceTiers, tiers } from './lib/advanceTiers';
import {
  power,
  powerAdvances,
  powerCitizens,
  powerGold,
  powerUnits,
} from './lib/power';
import {
  score,
  scoreCitizens,
  scorePollution,
  scoreWonders,
} from './lib/score';
import Advance from '@civ-clone/core-science/Advance';
import PlayerTile from '@civ-clone/core-player-world/PlayerTile';
import Unit from '@civ-clone/core-unit/Unit';
import { StrategyRegistry } from '@civ-clone/core-strategy/StrategyRegistry';
import World from '@civ-clone/core-world/World';
import Yield from '@civ-clone/core-yield/Yield';
import {
  calculateCitizenState,
  citizenSummary,
} from '@civ-clone/civ1-city-happiness/lib/calculateCitizenState';
import { instance as cityBuildRegistryInstance } from '@civ-clone/core-city-build/CityBuildRegistry';
import { instance as cityGrowthRegistryInstance } from '@civ-clone/core-city-growth/CityGrowthRegistry';
import { instance as cityRegistryInstance } from '@civ-clone/core-city/CityRegistry';
import { instance as clientRegistryInstance } from '@civ-clone/core-client/ClientRegistry';
import { instance as engine } from '@civ-clone/core-engine/Engine';
import { instance as playerGovernmentRegistryInstance } from '@civ-clone/core-government/PlayerGovernmentRegistry';
import { instance as playerRegistryInstance } from '@civ-clone/core-player/PlayerRegistry';
import { instance as advanceRegistryInstance } from '@civ-clone/core-science/AdvanceRegistry';
import { instance as playerResearchRegistryInstance } from '@civ-clone/core-science/PlayerResearchRegistry';
import { instance as playerTreasuryRegistryInstance } from '@civ-clone/core-treasury/PlayerTreasuryRegistry';
import { instance as playerWorldRegistryInstance } from '@civ-clone/core-player-world/PlayerWorldRegistry';
import { instance as ruleRegistryInstance } from '@civ-clone/core-rule/RuleRegistry';
import { instance as specialistRegistryInstance } from '@civ-clone/core-city/SpecialistRegistry';
import { instance as tileImprovementRegistryInstance } from '@civ-clone/core-tile-improvement/TileImprovementRegistry';
import { instance as unitRegistryInstance } from '@civ-clone/core-unit/UnitRegistry';
import { instance as wonderRegistryInstance } from '@civ-clone/core-wonder/WonderRegistry';

export const START = '<<<arena';
export const END = 'arena>>>';

type Role = 'baseline' | 'candidate';

// What `tools/arena.js` generates for each variant.
type Variant = {
  label: string;
  // The variant's own class. Its `Rules/` find their client with `instanceof` it, so each variant's rules only ever
  //  reach that variant's seats.
  SimpleAIClient: new (...args: any[]) => any;
  // Filled in when the plugin list reaches the variant's `registerStrategies`, where the installed package's
  //  `index.ts` would have loaded it.
  strategies: {
    createStrategies?: (dependencies: unknown) => unknown[];
    dependenciesFor?: (game: unknown) => unknown;
    // `core-game`'s `defaultGame`, captured there too rather than imported here, which would evaluate `core-game`
    //  ahead of the plugin list.
    game?: unknown;
  };
  // Where `strategyRegistry` sits in the constructor, `player` being 0: read from the variant's source.
  strategyRegistryIndex: number;
};

const supplied = JSON.parse(process.env.ARENA_CONFIG || '{}');
const seating: Role[] = supplied.seating ?? [];
const verbose: boolean = supplied.verbose ?? false;
const { baseline, candidate }: { baseline: Variant; candidate: Variant } =
  variants;

type Seat = {
  seat: number;
  role: Role;
  player: Player;
  client: any;
  disorderTurns: Set<number>;
  disorderCityTurns: number;
  loopGuardHits: number;
  loopGuardTurns: Set<number>;
  unitsSkipped: number;
  skipTurns: Set<number>;
  unhandledActions: number;
  unitsCreated: number;
  navalUnitsCreated: number;
  unitsLost: number;
  unitsLostAtSea: number;
  unitsDefeated: number;
  eliminatedTurn: number | null;
  // Each city's Wonders, as `<city id>:<Wonder>`, seen being built at a turn's start.
  wondersStarted: Set<string>;
  wondersBuilt: number;
  improvementsBuilt: number;
  firstCityTurn: number | null;
  noCityAtTurn: boolean;
  // The tax, science and luxury rates at the latest turn start, and how often they had changed since the last one.
  rates: number[] | null;
  rateChanges: number;
  luxuriesTotal: number;
  rateTurns: number;
  // How many advances the player held at the first turn's start: v474.05's power ranking doesn't count them.
  advancesAtStart: number | null;
  // Specialists summed over the turn starts: citizen-turns spent off the map.
  specialistTurns: number;
};

// The turn at whose start `noCityAtTurn10` checks for a city, or the last turn of a shorter game.
const NO_CITY_TURN = 10;

const seats: Seat[] = [];
const checksums: { [turn: number]: string } = {};
let world: World | null = null;
let stopped = false;
let currentTurn = 0;
let errorsLogged = 0;

const fail = (reason: string, error?: unknown): never => {
  process.stderr.write(
    `${reason}\n${error instanceof Error ? error.stack : String(error ?? '')}\n`
  );
  process.exit(1);

  throw new Error(reason);
};

// The AI's loop guard dumps whole units to the console, and a unit it skips logs its error. Neither draws a random
//  number or touches state, so they are counted below rather than printed. `--verbose` lets them through.
if (!verbose) {
  console.log = (): void => {};
  console.error = (): void => {
    errorsLogged += 1;
  };
}

// As `run.ts`: the turn loop has no natural exit, so its events are swallowed once the game is over.
const LOOP_EVENTS = [
  'player:turn-end',
  'player:turn-start',
  'turn:end',
  'turn:start',
];
const emit = engine.emit.bind(engine);

engine.emit = (event: string, ...args: any[]): void => {
  if (stopped && LOOP_EVENTS.includes(event)) {
    return;
  }

  emit(event, ...args);
};

// Hooks the three places `SimpleAIClient` gives up on something, on the instance, so the count needs no change to
//  either variant and the method still runs exactly as it would have.
const instrument = (entry: Seat): void => {
  const client = entry.client;
  const actionLimitReached = client.actionLimitReached.bind(client);
  const actionFailed = client.actionFailed.bind(client);
  const unhandledAction = client.unhandledAction.bind(client);

  client.actionLimitReached = (action: unknown) => {
    entry.loopGuardHits += 1;
    entry.loopGuardTurns.add(currentTurn);

    return actionLimitReached(action);
  };

  client.actionFailed = (action: unknown, error: unknown) => {
    entry.unitsSkipped += 1;
    entry.skipTurns.add(currentTurn);

    return actionFailed(action, error);
  };

  client.unhandledAction = (action: { constructor: { name: string } }) => {
    if (action.constructor.name !== 'EndTurn') {
      entry.unhandledActions += 1;
    }

    return unhandledAction(action);
  };
};

const attempt = <T>(read: () => T, fallback: T): T => {
  try {
    return read();
  } catch (e) {
    return fallback;
  }
};

// By the name of a class in the prototype chain, so `library-unit` isn't imported (and evaluated) ahead of the plugin
//  list.
const isA = (value: object, name: string): boolean => {
  for (
    let prototype = Object.getPrototypeOf(value);
    prototype !== null;
    prototype = Object.getPrototypeOf(prototype)
  ) {
    if (prototype.constructor?.name === name) {
      return true;
    }
  }

  return false;
};

// The player's tax, science and luxury rates, in percent, read by name through the game the plugin list loaded, so
//  `core-trade-rate` isn't imported (and evaluated) ahead of it. `null` before the player has any.
const tradeRatesOf = (player: Player): number[] | null =>
  attempt(() => {
    const rates: { constructor: { name: string }; value(): number }[] = (
      baseline.strategies.game as any
    ).playerTradeRates
      .getByPlayer(player)
      .all();
    const rate = (name: string): number =>
      rates.find((rate) => rate.constructor.name === name)?.value() ?? 0;

    return [rate('Tax'), rate('Research'), rate('Luxuries')];
  }, null);

// Civ1's Civilization Score, as v474.05 adds it up (OpenCivOne's decompile, `Overlay_20`
//  `F20_0000_0ca9_ShowCivilizationScorePopup`; Rome on 640K a Day pp325-328 agrees). The terms the engine has no
//  concept for yet are left out, so are 0 here: Future Technology (5 each, civ-clone/web-renderer#128), world peace (3
//  a turn of it after AD 1, at most 100) and a landed spaceship. See docs/arena.md. The arithmetic is in `lib/score`;
//  the counts it's given are the engine's.

type CityScore = {
  // A happy citizen is worth 2, a content one or a specialist 1, an unhappy one nothing: the city's size, plus its happy
  //  citizens, less its unhappy ones.
  citizens: number;
  specialists: number;
  // Unhappy citizens made content by units in the city.
  martialLaw: number;
};

// By the engine's own reckoning of the city's citizens, with its trade rates as they are.
const scoreCity = (city: City): CityScore => {
  const cityGrowth = cityGrowthRegistryInstance.getByCity(city),
    yields: Yield[] = city.yields(),
    [unhappy, , happy] = citizenSummary(
      calculateCitizenState(cityGrowth, yields, specialistRegistryInstance)
    );

  return {
    citizens: scoreCitizens(cityGrowth.size(), happy, unhappy),
    specialists: specialistRegistryInstance.getByCity(city).length,
    martialLaw: yields
      .filter((cityYield) => isA(cityYield, 'MartialLaw'))
      .reduce((total, cityYield) => total + Math.abs(cityYield.value()), 0),
  };
};

// Polluted tiles anywhere in the world. v474.05 counts them all against each player's score, not just the ones the
//  player can see, as the book has it. Nothing in the engine pollutes a tile yet.
const pollutedTiles = (): number =>
  tileImprovementRegistryInstance.filter((improvement) =>
    isA(improvement, 'Pollution')
  ).length;

// Each advance's tier, worked out from the ruleset's `Requirements` once, at the end of the game.
let tierMap: Map<typeof Advance, number> | null = null;

// Each unit type's value, from the ruleset's `BuildCost` rules, looked up once.
const unitValues = new Map<typeof Unit, number>();

const tiersOf = (): Map<typeof Advance, number> =>
  (tierMap ??= tiers(ruleRegistryInstance, advanceRegistryInstance.entries()));

const results = () =>
  seats.map((entry) => {
    const { player } = entry;
    const cities = cityRegistryInstance.getByPlayer(player);
    const tiles: PlayerTile[] = attempt(
      () => playerWorldRegistryInstance.getByPlayer(player).entries(),
      []
    );
    const cityScores = cities.map(scoreCity);
    const sum = (key: keyof CityScore): number =>
      cityScores.reduce((total, cityScore) => total + cityScore[key], 0);
    const citizens = sum('citizens');
    const wonders = scoreWonders(
      wonderRegistryInstance.getByPlayer(player).length
    );
    const pollution = scorePollution(pollutedTiles());
    const total = score(citizens, wonders, pollution);
    const gold = attempt(
      () =>
        playerTreasuryRegistryInstance
          .getByPlayer(player)
          .find((treasury) => treasury.yield().name === 'Gold')
          ?.value() ?? 0,
      0
    );
    const known: (typeof Advance)[] = attempt(
      () =>
        playerResearchRegistryInstance
          .getByPlayer(player)
          .complete()
          .map((advance) => advance.constructor as typeof Advance),
      []
    );
    const population = cities.reduce(
      (total: number, city: City) =>
        total + cityGrowthRegistryInstance.getByCity(city).size(),
      0
    );
    const eliminated =
      entry.eliminatedTurn !== null || !playerRegistryInstance.includes(player);
    const powerGoldValue = powerGold(gold);
    const powerCitizensValue = powerCitizens(population);
    const powerAdvancesValue = powerAdvances(
      known.length - (entry.advancesAtStart ?? 0)
    );
    const powerUnitsValue = powerUnits(
      ruleRegistryInstance,
      unitRegistryInstance.getByPlayer(player),
      unitValues
    );

    return {
      seat: entry.seat,
      role: entry.role,
      civilization: attempt(
        () => player.civilization().constructor.name,
        'unknown'
      ),
      government: attempt(
        () =>
          playerGovernmentRegistryInstance.getByPlayer(player).get().constructor
            .name,
        'unknown'
      ),
      metrics: {
        // v474.05's power ranking: docs/arena.md.
        power: power(
          !eliminated,
          powerGoldValue,
          powerCitizensValue,
          powerAdvancesValue,
          powerUnitsValue
        ),
        powerGold: powerGoldValue,
        powerCitizens: powerCitizensValue,
        powerAdvances: powerAdvancesValue,
        powerUnits: powerUnitsValue,
        // Never below 0, as in v474.05.
        score: total,
        scoreCitizens: citizens,
        scoreWonders: wonders,
        scorePollution: pollution,
        advanceTiers: advanceTiers(tiersOf(), known),
        cities: cities.length,
        population,
        advances: attempt(
          () =>
            playerResearchRegistryInstance.getByPlayer(player).complete()
              .length,
          0
        ),
        units: unitRegistryInstance.getByPlayer(player).length,
        navalUnits: unitRegistryInstance
          .getByPlayer(player)
          .filter((unit) => isA(unit, 'Naval')).length,
        unitsCreated: entry.unitsCreated,
        navalUnitsCreated: entry.navalUnitsCreated,
        unitsLost: entry.unitsLost,
        unitsLostAtSea: entry.unitsLostAtSea,
        unitsDefeated: entry.unitsDefeated,
        wondersStarted: entry.wondersStarted.size,
        wondersBuilt: entry.wondersBuilt,
        improvementsBuilt: entry.improvementsBuilt,
        // A player that never founded a city counts as founding one on the last turn.
        firstCityTurn: entry.firstCityTurn ?? config.turns,
        noCityAtTurn10: entry.noCityAtTurn ? 1 : 0,
        // By name, so `civ1-treasury` isn't imported (and evaluated) ahead of the plugin list.
        gold,
        explored: tiles.length,
        exploredLand: tiles.filter((tile) => tile.isLand()).length,
        exploredSea: tiles.filter((tile) => tile.isWater()).length,
        disorderTurns: entry.disorderTurns.size,
        disorderCityTurns: entry.disorderCityTurns,
        specialists: sum('specialists'),
        specialistTurns: entry.specialistTurns,
        martialLaw: sum('martialLaw'),
        tax: entry.rates?.[0] ?? 0,
        science: entry.rates?.[1] ?? 0,
        luxuries: entry.rates?.[2] ?? 0,
        meanLuxuries:
          entry.rateTurns === 0 ? 0 : entry.luxuriesTotal / entry.rateTurns,
        rateChanges: entry.rateChanges,
        eliminated: eliminated ? 1 : 0,
        loopGuardTurns: entry.loopGuardTurns.size,
        loopGuardHits: entry.loopGuardHits,
        unitsSkipped: entry.unitsSkipped,
        skipTurns: entry.skipTurns.size,
        unhandledActions: entry.unhandledActions,
      },
      eliminatedTurn: entry.eliminatedTurn,
    };
  });

const finish = (): void => {
  stopped = true;

  process.stdout.write(
    `\n${START}\n${JSON.stringify({
      config,
      seating,
      variants: { baseline: baseline.label, candidate: candidate.label },
      turn: currentTurn,
      checksums,
      mathRandomCalls: mathRandomCalls(),
      errorsLogged,
      seats: results(),
    })}\n${END}\n`
  );

  process.exit(0);
};

ruleRegistryInstance.register(
  new Built(
    new Effect((built: World): void => {
      world = built;
    })
  )
);

engine.on('turn:start', (turn: number): void => {
  if (stopped) {
    return;
  }

  if (!world) {
    fail('turn started before the world was built');
  }

  currentTurn = turn;

  // Wonders being built, and who has no city yet: cheap enough to read every turn.
  seats.forEach((entry): void => {
    const cities = cityRegistryInstance.getByPlayer(entry.player);

    if (turn === Math.min(NO_CITY_TURN, config.turns)) {
      entry.noCityAtTurn = cities.length === 0;
    }

    if (entry.advancesAtStart === null) {
      entry.advancesAtStart = attempt(
        () =>
          playerResearchRegistryInstance.getByPlayer(entry.player).complete()
            .length,
        0
      );
    }

    const rates = tradeRatesOf(entry.player);

    if (rates !== null) {
      if (entry.rates !== null && rates.join('/') !== entry.rates.join('/')) {
        entry.rateChanges += 1;
      }

      entry.rates = rates;
      entry.luxuriesTotal += rates[2];
      entry.rateTurns += 1;
    }

    cities.forEach((city: City): void => {
      entry.specialistTurns +=
        specialistRegistryInstance.getByCity(city).length;

      const building = attempt(
        () => cityBuildRegistryInstance.getByCity(city).building()?.item(),
        undefined
      );

      if (building && isA(building.prototype, 'Wonder')) {
        entry.wondersStarted.add(`${city.id()}:${building.name}`);
      }
    });
  });

  // Only `--self-check`'s conformance game asks for these: they cost more than the game does.
  if (config.checkpoints.includes(turn)) {
    checksums[turn] = checksum(
      snapshot(turn, random.calls(), world!, mathRandomCalls())
    );
  }

  if (turn >= config.turns) {
    finish();
  }
});

// Emitted by `civ1-city-happiness` at each player's turn start, once per city in disorder.
engine.on('city:civil-disorder', (city: City): void => {
  const entry = seats.find((seat) => seat.player === city.player());

  if (!entry) {
    return;
  }

  entry.disorderCityTurns += 1;
  entry.disorderTurns.add(currentTurn);
});

const seatOf = (player: Player | null | undefined): Seat | undefined =>
  seats.find((seat) => seat.player === player);

// `civ1-unit`'s. Built or from a hut. The starting units are created before turn 1 and left out.
engine.on('unit:created', (unit: Unit): void => {
  const entry = seatOf(unit.player());

  if (!entry || currentTurn === 0) {
    return;
  }

  entry.unitsCreated += 1;

  if (isA(unit, 'Naval')) {
    entry.navalUnitsCreated += 1;
  }
});

// `civ1-unit`'s: a unit lost in combat, and the unit that beat it.
engine.on('unit:defeated', (unit: Unit, by: Unit | null): void => {
  const lost = seatOf(unit.player());
  const won = by ? seatOf(by.player()) : undefined;

  if (lost) {
    lost.unitsLost += 1;
  }

  if (won) {
    won.unitsDefeated += 1;
  }
});

// `civ1-unit`'s: a Trireme that ended its moves away from the coast, or an aircraft out of fuel. Only the unit the
//  event names is counted, not any cargo lost with it.
engine.on('unit:lost-at-sea', (unit: Unit): void => {
  const entry = seatOf(unit.player());

  if (entry) {
    entry.unitsLostAtSea += 1;
  }
});

// `civ1-city`'s: a city founded. A captured city isn't counted.
engine.on('city:created', (city: City): void => {
  const entry = seatOf(city.player());

  if (entry && entry.firstCityTurn === null) {
    entry.firstCityTurn = currentTurn;
  }
});

// `civ1-city`'s: anything a city finishes. A Wonder is a `CityImprovement` too, so it's counted only as a Wonder.
engine.on(
  'city:building-complete',
  (cityBuild: { city(): City }, built: object | null): void => {
    const entry = seatOf(cityBuild.city().player());

    if (!entry || !built) {
      return;
    }

    if (isA(built, 'Wonder')) {
      entry.wondersBuilt += 1;
    } else if (isA(built, 'CityImprovement')) {
      entry.improvementsBuilt += 1;
    }
  }
);

engine.on('player:defeated', (player: Player): void => {
  const entry = seats.find((seat) => seat.player === player);

  if (entry && entry.eliminatedTurn === null) {
    entry.eliminatedTurn = currentTurn;
  }
});

// Each variant's strategies, built once per game over the game's registries and shared by that variant's seats, as
//  the game-wide registry is shared by every seat in a normal game.
const registryFor = (() => {
  const registries = new Map<Variant, StrategyRegistry>();

  return (variant: Variant): StrategyRegistry => {
    if (!registries.has(variant)) {
      const { createStrategies, dependenciesFor, game } = variant.strategies;

      if (!createStrategies || !dependenciesFor || !game) {
        fail(`${variant.label}: the plugin list never loaded its strategies`);
      }

      const registry = new StrategyRegistry();

      registry.register(
        ...(createStrategies!(dependenciesFor!(game)) as any[])
      );
      registries.set(variant, registry);
    }

    return registries.get(variant)!;
  };
})();

// As `run.ts`, but each seat's client is its variant's, given that variant's strategies. Everything else is left to
//  the constructor's defaults, which are the same singletons `run.ts` plays on.
engine.on('engine:start', (): void => {
  new Array(config.players).fill(0).forEach((_, seat): void => {
    const role = seating[seat];

    if (role !== 'baseline' && role !== 'candidate') {
      fail(`no variant for seat ${seat}: ${JSON.stringify(seating)}`);
    }

    const variant = role === 'baseline' ? baseline : candidate;
    const registry = registryFor(variant);
    const player = new Player();
    const args: unknown[] = new Array(variant.strategyRegistryIndex + 1).fill(
      undefined
    );

    args[0] = player;
    args[variant.strategyRegistryIndex] = registry;

    const client = new variant.SimpleAIClient(...args);

    // A constructor that moved `strategyRegistry` would otherwise play on the game-wide registry, which is the
    //  installed package's, silently.
    if (client._strategyRegistry !== registry) {
      fail(`${variant.label}: the client did not take the arena's strategies`);
    }

    playerRegistryInstance.register(player);
    clientRegistryInstance.register(client);

    const entry: Seat = {
      seat,
      role,
      player,
      client,
      disorderTurns: new Set(),
      disorderCityTurns: 0,
      loopGuardHits: 0,
      loopGuardTurns: new Set(),
      unitsSkipped: 0,
      skipTurns: new Set(),
      unhandledActions: 0,
      unitsCreated: 0,
      navalUnitsCreated: 0,
      unitsLost: 0,
      unitsLostAtSea: 0,
      unitsDefeated: 0,
      eliminatedTurn: null,
      wondersStarted: new Set(),
      wondersBuilt: 0,
      improvementsBuilt: 0,
      firstCityTurn: null,
      noCityAtTurn: false,
      rates: null,
      rateChanges: 0,
      luxuriesTotal: 0,
      rateTurns: 0,
      advancesAtStart: null,
      specialistTurns: 0,
    };

    instrument(entry);
    seats.push(entry);
  });
});

engine.setOption('players', config.players);
engine.setOption('height', config.height);
engine.setOption('width', config.width);

process.on('uncaughtException', (error) => fail('uncaught exception', error));
process.on('unhandledRejection', (error) => fail('unhandled rejection', error));

engine.start();

import('../../src/js/plugins')
  .then(() => engine.emit('plugins:load:end'))
  .catch((error) => fail('failed to load plugins', error));
